name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    paths: '**.c'
  pull_request:
    branches: [ "main" ]

jobs:
  Test-Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install valgrind
      run: sudo apt install valgrind
    - name: Test
      run: make all_test
    - name: Memory Leaks
      run: |
           sudo chmod +x ./valgrind-test.sh
           ./valgrind-test.sh

  Test-Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install make
      run:  choco install make
    - name: Run tests
      run: make all_test
