name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    paths: '**.c'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Test-Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install valgrind
      run: |
           sudo apt-get update -y
           sudo apt-get install valgrind -y
    - name: Test
      run: make test
    - name: Memory Leaks
      run: |
           sudo chmod +x ./valgrind-test.sh
           ./valgrind-test.sh

  Test-Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: make test
