name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    paths: '**.c'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Test-Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: make test
    - name: Memory Leaks
      run: |
           sudo apt-get update -y
           sudo apt-get install valgrind -y
           sudo chmod +x ./test/valgrind-test.sh
           ./test/valgrind-test.sh
    - name: Code sanitizer
      run: |
           sudo apt-get install cppcheck
           sudo chmod +x ./test/sanitize-code.sh
           ./test/sanitize-code.sh


  Test-Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: make test CC=gcc
