name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: make all_test
    - name: Memory Leaks
      run:  for t in ./bin/*; do valgrind --leak-check=yes --error-exitcode=1 "$t"; done 
